### ISSUE TITLE
Install Guide

### ISSUE THREAD

**Issue by Deepnerd** [imneonizer/autolycus#28]
can you please add some installation guide?  Thank you!

**Comment by navpret** [comment]
Yeah, really need it. Please guys 🙏. Had always been looking for this and when I found exactly the thing I needed, there are no instructions on how to install 😔. Also, I think you'd get many stars if you add guide

**Comment by imneonizer** [comment]
Thank you for appreciating the project, I myself have been looking for a similar solution for years but since I didn't found any. I decided to build it on my own.

Since the project didn't attract a lot of enthusiasts, I focused more on improving features.
If anyone knows how to use `docker` and `docker-compose` then it's pretty straigh forward to run.

Just run the below command from application's root directory and visit `localhost:3000`
````
sudo docker-compose up
````

I will take out some time to write installation and configuration instructions soon or later.
